using AppJogoDaForca.Models;

namespace AppJogoDaForca.Repositories
{
    // guarda a lista de palavras 
    internal class WordRepositories
    {
        private List<Word> _words;
        public WordRepositories()
        {
            _words = new List<Word>();
            _words.Add(new Word("Nome", "Maria".ToUpper()));
            _words.Add(new Word("Profissão", "Engenheiro".ToUpper()));
            _words.Add(new Word("Profissão", "Pedreiro".ToUpper()));
            _words.Add(new Word("Profissão", "Cabeleireiro".ToUpper()));
            _words.Add(new Word("Profissão", "Policial".ToUpper()));
            _words.Add(new Word("Vegetal", "Cenoura".ToUpper()));
            _words.Add(new Word("Fruta", "Abacate".ToUpper()));
            _words.Add(new Word("Animal", "Gato".ToUpper()));
            _words.Add(new Word("País", "Brasil".ToUpper()));
            _words.Add(new Word("Cor", "Azul".ToUpper()));
            _words.Add(new Word("Profissão", "Medico".ToUpper()));
            _words.Add(new Word("Esporte", "Futebol".ToUpper()));
            _words.Add(new Word("Comida", "Pizza".ToUpper()));
            _words.Add(new Word("Instrumento Musical", "Violino".ToUpper()));
            _words.Add(new Word("Sobremesa", "Sorvete".ToUpper()));
            _words.Add(new Word("Filme", "Matrix".ToUpper()));
            _words.Add(new Word("Idioma", "Ingles".ToUpper()));
            _words.Add(new Word("Cidade", "Paris".ToUpper()));
            _words.Add(new Word("Personagem de Desenho", "Mickey".ToUpper()));
            _words.Add(new Word("Marca de Carro", "Toyota".ToUpper()));
            _words.Add(new Word("Planta", "Rosa".ToUpper()));
            _words.Add(new Word("Bebida", "Cafe".ToUpper()));
            _words.Add(new Word("Profissão", "Advogado".ToUpper()));
            _words.Add(new Word("Planeta", "Marte".ToUpper()));
            _words.Add(new Word("Animal", "Elefante".ToUpper()));
            _words.Add(new Word("País", "Japao".ToUpper()));
            _words.Add(new Word("Cor", "Verde".ToUpper()));
            _words.Add(new Word("Esporte", "Basquete".ToUpper()));
            _words.Add(new Word("Comida", "Hamburger".ToUpper()));
            _words.Add(new Word("Instrumento Musical", "Piano".ToUpper()));
            _words.Add(new Word("Sobremesa", "Brigadeiro".ToUpper()));
            _words.Add(new Word("Filme", "Titanic".ToUpper()));
            _words.Add(new Word("Idioma", "Espanhol".ToUpper()));
            _words.Add(new Word("Cidade", "Nova York".ToUpper()));
            _words.Add(new Word("Personagem de Desenho", "Bob Esponja".ToUpper()));
            _words.Add(new Word("Marca de Carro", "Ford".ToUpper()));
            _words.Add(new Word("Planta", "Girassol".ToUpper()));
            _words.Add(new Word("Bebida", "Refrigerante".ToUpper()));
            _words.Add(new Word("Planeta", "Saturno".ToUpper()));
            _words.Add(new Word("Profissão", "Professor".ToUpper()));
            _words.Add(new Word("Profissão", "Programador".ToUpper()));
            _words.Add(new Word("Profissão", "Arquiteto".ToUpper()));
            _words.Add(new Word("Profissão", "Designer".ToUpper()));
            _words.Add(new Word("Profissão", "Chef de cozinha".ToUpper()));
            _words.Add(new Word("Profissão", "Piloto".ToUpper()));
            _words.Add(new Word("Profissão", "Jornalista".ToUpper()));
            _words.Add(new Word("Profissão", "Bombeiro".ToUpper()));
            _words.Add(new Word("Profissão", "Fotógrafo".ToUpper()));
            _words.Add(new Word("Profissão", "Artista".ToUpper()));
            _words.Add(new Word("Hobby", "Pintura".ToUpper()));
            _words.Add(new Word("Hobby", "Danca".ToUpper()));
            _words.Add(new Word("Hobby", "Caminhada".ToUpper()));
            _words.Add(new Word("Hobby", "Fotografia".ToUpper()));
            _words.Add(new Word("Hobby", "Leitura".ToUpper()));
            _words.Add(new Word("Hobby", "Cozinhar".ToUpper()));
            _words.Add(new Word("Hobby", "Jardinagem".ToUpper()));
            _words.Add(new Word("Hobby", "Musica".ToUpper()));
            _words.Add(new Word("Meio de Transporte", "Bicicleta".ToUpper()));
            _words.Add(new Word("Meio de Transporte", "Aviao".ToUpper()));
            _words.Add(new Word("Meio de Transporte", "Navio".ToUpper()));
            _words.Add(new Word("Meio de Transporte", "Caminhao".ToUpper()));
            _words.Add(new Word("Meio de Transporte", "Helicoptero".ToUpper()));
            _words.Add(new Word("Meio de Transporte", "Trem".ToUpper()));
            _words.Add(new Word("Meio de Transporte", "Onibus".ToUpper()));
            _words.Add(new Word("Meio de Transporte", "Carro".ToUpper()));
            _words.Add(new Word("Ferramenta", "Martelo".ToUpper()));
            _words.Add(new Word("Ferramenta", "Chave de fenda".ToUpper()));
            _words.Add(new Word("Ferramenta", "Serra".ToUpper()));
            _words.Add(new Word("Ferramenta", "Alicate".ToUpper()));
            _words.Add(new Word("Ferramenta", "Broca".ToUpper()));
            _words.Add(new Word("Ferramenta", "Lixa".ToUpper()));
            _words.Add(new Word("Ferramenta", "Serrote".ToUpper()));
            _words.Add(new Word("Ferramenta", "Trena".ToUpper()));
            _words.Add(new Word("Hobby", "Viagem".ToUpper()));
            _words.Add(new Word("Hobby", "Surfe".ToUpper()));
            _words.Add(new Word("Hobby", "Artesanato".ToUpper()));
            _words.Add(new Word("Hobby", "Yoga".ToUpper()));
            _words.Add(new Word("Hobby", "Ciclismo".ToUpper()));
            _words.Add(new Word("Hobby", "Escalada".ToUpper()));
            _words.Add(new Word("Hobby", "Pesca".ToUpper()));
            _words.Add(new Word("Hobby", "Escrita".ToUpper()));
            _words.Add(new Word("Hobby", "Costura".ToUpper()));
            _words.Add(new Word("Hobby", "Jogos de Tabuleiro".ToUpper()));
            _words.Add(new Word("Hobby", "Jogos de Cartas".ToUpper()));
            _words.Add(new Word("Hobby", "Programação".ToUpper()));
            _words.Add(new Word("Hobby", "Teatro".ToUpper()));
            _words.Add(new Word("Hobby", "Desenho".ToUpper()));
            _words.Add(new Word("Hobby", "Fotografia".ToUpper()));
            _words.Add(new Word("Hobby", "Meditar".ToUpper()));
            _words.Add(new Word("Meio de Transporte", "Moto".ToUpper()));
            _words.Add(new Word("Meio de Transporte", "Barco".ToUpper()));
            _words.Add(new Word("Meio de Transporte", "Canoa".ToUpper()));
            _words.Add(new Word("Meio de Transporte", "Jet ski".ToUpper()));
            _words.Add(new Word("Ferramenta", "Tesoura".ToUpper()));
            _words.Add(new Word("Ferramenta", "Furadeira".ToUpper()));
            _words.Add(new Word("Ferramenta", "Plaina".ToUpper()));
            _words.Add(new Word("Ferramenta", "Chave inglesa".ToUpper()));
            _words.Add(new Word("Ferramenta", "Marreta".ToUpper()));
            _words.Add(new Word("Ferramenta", "Trena a laser".ToUpper()));
            _words.Add(new Word("Cor", "Cinza".ToUpper()));
            _words.Add(new Word("Acessório", "Pulseira".ToUpper()));
            _words.Add(new Word("Acessório", "Relogio".ToUpper()));
            _words.Add(new Word("Fruta", "Manga".ToUpper()));
            _words.Add(new Word("Fruta", "Melancia".ToUpper()));
            _words.Add(new Word("Fruta", "Laranja".ToUpper()));
            _words.Add(new Word("Fruta", "Morango".ToUpper()));
            _words.Add(new Word("Fruta", "Uva".ToUpper()));
            _words.Add(new Word("Fruta", "Pera".ToUpper()));
            _words.Add(new Word("Fruta", "Maçã".ToUpper()));
            _words.Add(new Word("Fruta", "Abacaxi".ToUpper()));
            _words.Add(new Word("Fruta", "Kiwi".ToUpper()));
            _words.Add(new Word("Fruta", "Cabeludo".ToUpper()));
            _words.Add(new Word("Animal", "Cachorro".ToUpper()));
            _words.Add(new Word("Animal", "Pássaro".ToUpper()));
            _words.Add(new Word("Animal", "Cavalo".ToUpper()));
            _words.Add(new Word("Animal", "Coelho".ToUpper()));
            _words.Add(new Word("Animal", "Leão".ToUpper()));
            _words.Add(new Word("Animal", "Tigre".ToUpper()));
            _words.Add(new Word("Animal", "Urso".ToUpper()));
            _words.Add(new Word("Animal", "Peixe".ToUpper()));
            _words.Add(new Word("Animal", "Cobra".ToUpper()));
            _words.Add(new Word("Animal", "Pinguim".ToUpper()));
            _words.Add(new Word("Cor", "Amarelo".ToUpper()));
            _words.Add(new Word("Cor", "Rosa".ToUpper()));
            _words.Add(new Word("Cor", "Marrom".ToUpper()));
            _words.Add(new Word("Cor", "Roxo".ToUpper()));
            _words.Add(new Word("Cor", "Laranja".ToUpper()));
            _words.Add(new Word("Esporte", "Tênis".ToUpper()));
            _words.Add(new Word("Esporte", "Natação".ToUpper()));
            _words.Add(new Word("Esporte", "Vôlei".ToUpper()));
            _words.Add(new Word("Esporte", "Ciclismo".ToUpper()));
            _words.Add(new Word("Esporte", "Corrida".ToUpper()));
            _words.Add(new Word("Esporte", "Skate".ToUpper()));
            _words.Add(new Word("Esporte", "Surfe".ToUpper()));
            _words.Add(new Word("Esporte", "Mergulho".ToUpper()));
            _words.Add(new Word("Esporte", "Boxe".ToUpper()));
            _words.Add(new Word("Instrumento Musical", "Guitarra".ToUpper()));
            _words.Add(new Word("Instrumento Musical", "Saxofone".ToUpper()));
            _words.Add(new Word("Instrumento Musical", "Bateria".ToUpper()));
            _words.Add(new Word("Instrumento Musical", "Flauta".ToUpper()));
            _words.Add(new Word("Instrumento Musical", "Trompete".ToUpper()));
            _words.Add(new Word("Instrumento Musical", "Saxofone".ToUpper()));
            _words.Add(new Word("Instrumento Musical", "Clarinete".ToUpper()));
            _words.Add(new Word("Instrumento Musical", "Trombone".ToUpper()));
            _words.Add(new Word("Marca de Carro", "Chevrolet".ToUpper()));
            _words.Add(new Word("Marca de Carro", "Honda".ToUpper()));
            _words.Add(new Word("Marca de Carro", "Nissan".ToUpper()));
            _words.Add(new Word("Marca de Carro", "Hyundai".ToUpper()));
            _words.Add(new Word("Marca de Carro", "Volkswagen".ToUpper()));
            _words.Add(new Word("Marca de Carro", "Audi".ToUpper()));
            _words.Add(new Word("Marca de Carro", "BMW".ToUpper()));
            _words.Add(new Word("Marca de Carro", "Mercedes".ToUpper()));
            _words.Add(new Word("Marca de Carro", "Kia".ToUpper()));
            _words.Add(new Word("Marca de Carro", "Fiat".ToUpper()));
            _words.Add(new Word("Instrumento Musical", "Gaita".ToUpper()));
            _words.Add(new Word("Instrumento Musical", "Ocarina".ToUpper()));
            _words.Add(new Word("Objeto de Estudo", "Astronomia".ToUpper()));
            _words.Add(new Word("Objeto de Estudo", "Química".ToUpper()));
            _words.Add(new Word("Objeto de Estudo", "Botânica".ToUpper()));
            _words.Add(new Word("Objeto de Estudo", "Antropologia".ToUpper()));
            _words.Add(new Word("Objeto de Estudo", "Geologia".ToUpper()));
            _words.Add(new Word("Objeto de Estudo", "História".ToUpper()));
            _words.Add(new Word("Objeto de Estudo", "Física".ToUpper()));
            _words.Add(new Word("Objeto de Estudo", "Matemática".ToUpper()));
            _words.Add(new Word("Objeto de Estudo", "Sociologia".ToUpper()));
            _words.Add(new Word("Objeto de Estudo", "Psicologia".ToUpper()));
            _words.Add(new Word("País", "Países Baixos".ToUpper()));
            _words.Add(new Word("País", "Nepal".ToUpper()));
            _words.Add(new Word("País", "Eslováquia".ToUpper()));
            _words.Add(new Word("País", "Malásia".ToUpper()));
            _words.Add(new Word("País", "Singapura".ToUpper()));
            _words.Add(new Word("País", "Estônia".ToUpper()));
            _words.Add(new Word("País", "Eslovênia".ToUpper()));
            _words.Add(new Word("País", "Marrocos".ToUpper()));
            _words.Add(new Word("País", "Costa Rica".ToUpper()));
            _words.Add(new Word("País", "Jordânia".ToUpper()));
            _words.Add(new Word("Cidade", "Zurique".ToUpper()));
            _words.Add(new Word("Cidade", "Budapeste".ToUpper()));
            _words.Add(new Word("Cidade", "Praga".ToUpper()));
            _words.Add(new Word("Cidade", "Roterdã".ToUpper()));
            _words.Add(new Word("Cidade", "Helsinque".ToUpper()));
            _words.Add(new Word("Cidade", "Bruxelas".ToUpper()));
            _words.Add(new Word("Cidade", "Vilnius".ToUpper()));
            _words.Add(new Word("Cidade", "Dublim".ToUpper()));
            _words.Add(new Word("Cidade", "Oslo".ToUpper()));
            _words.Add(new Word("Cidade", "Copenhague".ToUpper()));
            _words.Add(new Word("Obra de Arte", "Mona Lisa".ToUpper()));
            _words.Add(new Word("Obra de Arte", "O Grito".ToUpper()));
            _words.Add(new Word("Obra de Arte", "Noite Estrelada".ToUpper()));
            _words.Add(new Word("Obra de Arte", "A Última Ceia".ToUpper()));
            _words.Add(new Word("Obra de Arte", "A Criação de Adão".ToUpper()));
            _words.Add(new Word("Obra de Arte", "A Persistência da Memória".ToUpper()));
            _words.Add(new Word("Obra de Arte", "O Nascimento de Vênus".ToUpper()));
            _words.Add(new Word("Obra de Arte", "Guernica".ToUpper()));
            _words.Add(new Word("Obra de Arte", "O Beijo".ToUpper()));
            _words.Add(new Word("Obra de Arte", "A Escola de Atenas".ToUpper()));
            _words.Add(new Word("Profissão", "Neurocirurgião".ToUpper()));
            _words.Add(new Word("Profissão", "Oftalmologista".ToUpper()));
            _words.Add(new Word("Profissão", "Pediatra".ToUpper()));
            _words.Add(new Word("Profissão", "Ginecologista".ToUpper()));
            _words.Add(new Word("Profissão", "Cardiologista".ToUpper()));
            _words.Add(new Word("Profissão", "Ortopedista".ToUpper()));
            _words.Add(new Word("Profissão", "Oncologista".ToUpper()));
            _words.Add(new Word("Profissão", "Radiologista".ToUpper()));
            _words.Add(new Word("Profissão", "Urologista".ToUpper()));
            _words.Add(new Word("Profissão", "Dermatologista".ToUpper()));
            _words.Add(new Word("Edifício", "Museu do Louvre".ToUpper()));
            _words.Add(new Word("Edifício", "Torre Eiffel".ToUpper()));
            _words.Add(new Word("Edifício", "Big Ben".ToUpper()));
            _words.Add(new Word("Edifício", "Empire State Building".ToUpper()));
            _words.Add(new Word("Edifício", "Coliseu".ToUpper()));
            _words.Add(new Word("Edifício", "Ópera de Sydney".ToUpper()));
            _words.Add(new Word("Edifício", "Torre de Pisa".ToUpper()));
            _words.Add(new Word("Edifício", "Catedral de Notre-Dame".ToUpper()));
            _words.Add(new Word("Edifício", "Torre de Belém".ToUpper()));
            _words.Add(new Word("Idioma", "Francês".ToUpper()));
            _words.Add(new Word("Idioma", "Italiano".ToUpper()));
            _words.Add(new Word("Idioma", "Alemão".ToUpper()));
            _words.Add(new Word("Idioma", "Russo".ToUpper()));
            _words.Add(new Word("Idioma", "Árabe".ToUpper()));
            _words.Add(new Word("Idioma", "Japonês".ToUpper()));
            _words.Add(new Word("Idioma", "Chinês".ToUpper()));
            _words.Add(new Word("Idioma", "Coreano".ToUpper()));
            _words.Add(new Word("Idioma", "Hebraico".ToUpper()));
            _words.Add(new Word("Idioma", "Húngaro".ToUpper()));
            _words.Add(new Word("Instrumento Musical", "Ukulele".ToUpper()));
            _words.Add(new Word("Instrumento Musical", "Sanfona".ToUpper()));
            _words.Add(new Word("Livro", "Dom Quixote".ToUpper()));
            _words.Add(new Word("Livro", "Orgulho e Preconceito".ToUpper()));
            _words.Add(new Word("Livro", "O Senhor dos Anéis".ToUpper()));
            _words.Add(new Word("Livro", "O Hobbit".ToUpper()));
            _words.Add(new Word("Livro", "Cem Anos de Solidão".ToUpper()));
            _words.Add(new Word("Livro", "O Grande Gatsby".ToUpper()));
            _words.Add(new Word("Livro", "A Revolução dos Bichos".ToUpper()));
            _words.Add(new Word("Livro", "A Moreninha".ToUpper()));
            _words.Add(new Word("Livro", "A Divina Comédia".ToUpper()));
        }

        public Word GetRandomWord()
        {
            Random rand = new Random(); 
            var number = rand.Next(0, _words.Count);
            return _words[number];
        }
    }
}
